{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMjcReMIuAWfl4HJf/8GRnn",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/mypotato20-ops/income_tax.py/blob/main/%ED%8C%80%EB%B3%84%EC%9D%BC%EC%A0%95%EA%B3%B5%EC%9C%A0.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 404
        },
        "id": "v_ZScXLwuenb",
        "outputId": "3ae10d82-daf3-4018-be49-0b422768019c"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'streamlit'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipython-input-2725671994.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mstreamlit\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mplotly\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexpress\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpx\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mdatetime\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdatetime\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimedelta\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcalendar\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'streamlit'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "from datetime import datetime, timedelta\n",
        "import calendar\n",
        "import sys\n",
        "import os\n",
        "\n",
        "sys.path.append(os.path.dirname(os.path.abspath(__file__)))\n",
        "\n",
        "from utils.data_manager import (\n",
        "    load_members, add_schedule, delete_schedule,\n",
        "    add_member, get_member_by_id, check_conflicts,\n",
        "    get_statistics, load_schedules\n",
        ")\n",
        "\n",
        "st.set_page_config(page_title=\"팀 일정 관리\", page_icon=\"📅\", layout=\"wide\")\n",
        "\n",
        "# 세션 상태 초기화\n",
        "if 'current_date' not in st.session_state:\n",
        "    st.session_state.current_date = datetime.now()\n",
        "if 'selected_member' not in st.session_state:\n",
        "    st.session_state.selected_member = 'all'\n",
        "if 'view' not in st.session_state:\n",
        "    st.session_state.view = 'calendar'\n",
        "if 'notifications' not in st.session_state:\n",
        "    st.session_state.notifications = []\n",
        "if 'show_add_modal' not in st.session_state:\n",
        "    st.session_state.show_add_modal = False\n",
        "\n",
        "members = load_members()\n",
        "schedules = load_schedules()\n",
        "stats = get_statistics()\n",
        "\n",
        "st.markdown(\"\"\"\n",
        "<style>\n",
        ".schedule-item {\n",
        "    padding: 8px;\n",
        "    margin: 4px 0;\n",
        "    border-radius: 5px;\n",
        "    font-size: 0.85em;\n",
        "}\n",
        "</style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "st.title(\"📅 팀 일정 관리 시스템\")\n",
        "\n",
        "col1, col2, col3, col4 = st.columns([2, 2, 2, 6])\n",
        "with col1:\n",
        "    if st.button(\"📅 캘린더\", use_container_width=True):\n",
        "        st.session_state.view = 'calendar'\n",
        "        st.rerun()\n",
        "with col2:\n",
        "    if st.button(\"📊 통계\", use_container_width=True):\n",
        "        st.session_state.view = 'stats'\n",
        "        st.rerun()\n",
        "with col3:\n",
        "    if st.button(\"👥 팀원 관리\", use_container_width=True):\n",
        "        st.session_state.view = 'members'\n",
        "        st.rerun()\n",
        "\n",
        "st.markdown(\"---\")\n",
        "\n",
        "if st.session_state.notifications:\n",
        "    for i, notif in enumerate(st.session_state.notifications):\n",
        "        col1, col2 = st.columns([10, 1])\n",
        "        with col1:\n",
        "            st.warning(f\"⚠️ {notif}\")\n",
        "        with col2:\n",
        "            if st.button(\"✕\", key=f\"close_{i}\"):\n",
        "                st.session_state.notifications.pop(i)\n",
        "                st.rerun()\n",
        "\n",
        "# 캘린더 뷰\n",
        "if st.session_state.view == 'calendar':\n",
        "    col1, col2, col3, col4, col5, col6 = st.columns([1, 1, 1, 3, 2, 2])\n",
        "\n",
        "    with col1:\n",
        "        if st.button(\"◀\"):\n",
        "            st.session_state.current_date = st.session_state.current_date - timedelta(days=30)\n",
        "            st.rerun()\n",
        "    with col2:\n",
        "        if st.button(\"오늘\"):\n",
        "            st.session_state.current_date = datetime.now()\n",
        "            st.rerun()\n",
        "    with col3:\n",
        "        if st.button(\"▶\"):\n",
        "            st.session_state.current_date = st.session_state.current_date + timedelta(days=30)\n",
        "            st.rerun()\n",
        "    with col4:\n",
        "        st.markdown(f\"### {st.session_state.current_date.year}년 {st.session_state.current_date.month}월\")\n",
        "    with col5:\n",
        "        member_options = ['전체 팀원'] + [m['name'] for m in members]\n",
        "        selected_name = st.selectbox(\"팀원 필터\", member_options)\n",
        "        if selected_name == '전체 팀원':\n",
        "            st.session_state.selected_member = 'all'\n",
        "        else:\n",
        "            selected = next((m for m in members if m['name'] == selected_name), None)\n",
        "            st.session_state.selected_member = selected['id'] if selected else 'all'\n",
        "    with col6:\n",
        "        if st.button(\"➕ 일정 추가\", type=\"primary\"):\n",
        "            st.session_state.show_add_modal = not st.session_state.show_add_modal\n",
        "\n",
        "    if st.session_state.show_add_modal:\n",
        "        with st.container():\n",
        "            st.markdown(\"### ➕ 일정 추가\")\n",
        "            col1, col2 = st.columns(2)\n",
        "            with col1:\n",
        "                selected_member_name = st.selectbox(\"팀원\", [m['name'] for m in members], key='add_member')\n",
        "                schedule_type = st.selectbox(\"유형\", [\"연차\", \"반차\", \"병가\", \"출장\", \"재택근무\"])\n",
        "            with col2:\n",
        "                schedule_date = st.date_input(\"날짜\", value=datetime.now())\n",
        "                reason = st.text_area(\"사유 (선택)\", height=100)\n",
        "\n",
        "            col1, col2 = st.columns(2)\n",
        "            with col1:\n",
        "                if st.button(\"추가하기\", type=\"primary\", use_container_width=True):\n",
        "                    selected_member = next((m for m in members if m['name'] == selected_member_name), None)\n",
        "                    if selected_member:\n",
        "                        new_schedule = {\n",
        "                            'member_id': selected_member['id'],\n",
        "                            'type': schedule_type,\n",
        "                            'date': schedule_date.strftime('%Y-%m-%d'),\n",
        "                            'reason': reason\n",
        "                        }\n",
        "                        add_schedule(new_schedule)\n",
        "                        conflicts = check_conflicts(new_schedule['date'], new_schedule['member_id'])\n",
        "                        if len(conflicts) >= 2:\n",
        "                            st.session_state.notifications.append(\n",
        "                                f\"{new_schedule['date']}에 {len(conflicts) + 1}명이 휴가입니다.\"\n",
        "                            )\n",
        "                        st.session_state.show_add_modal = False\n",
        "                        st.success(\"일정이 추가되었습니다!\")\n",
        "                        st.rerun()\n",
        "            with col2:\n",
        "                if st.button(\"취소\", use_container_width=True):\n",
        "                    st.session_state.show_add_modal = False\n",
        "                    st.rerun()\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "\n",
        "    year = st.session_state.current_date.year\n",
        "    month = st.session_state.current_date.month\n",
        "    first_day = datetime(year, month, 1)\n",
        "    first_weekday = first_day.weekday()\n",
        "    if first_weekday == 6:\n",
        "        first_weekday = 0\n",
        "    else:\n",
        "        first_weekday += 1\n",
        "    days_in_month = calendar.monthrange(year, month)[1]\n",
        "\n",
        "    days_header = ['일', '월', '화', '수', '목', '금', '토']\n",
        "    cols = st.columns(7)\n",
        "    for i, day in enumerate(days_header):\n",
        "        with cols[i]:\n",
        "            st.markdown(f\"**{day}**\")\n",
        "\n",
        "    current_day = 1\n",
        "    week = 0\n",
        "\n",
        "    while current_day <= days_in_month:\n",
        "        cols = st.columns(7)\n",
        "        for col_idx in range(7):\n",
        "            with cols[col_idx]:\n",
        "                if week == 0 and col_idx < first_weekday:\n",
        "                    st.markdown(\"&nbsp;\")\n",
        "                elif current_day <= days_in_month:\n",
        "                    date_str = f\"{year}-{month:02d}-{current_day:02d}\"\n",
        "                    day_schedules = [s for s in schedules if s['date'] == date_str]\n",
        "                    if st.session_state.selected_member != 'all':\n",
        "                        day_schedules = [s for s in day_schedules if s['member_id'] == st.session_state.selected_member]\n",
        "\n",
        "                    st.markdown(f\"**{current_day}**\")\n",
        "\n",
        "                    for schedule in day_schedules[:3]:\n",
        "                        member = get_member_by_id(schedule['member_id'])\n",
        "                        if member:\n",
        "                            schedule_html = f\"\"\"\n",
        "                            <div class=\"schedule-item\" style=\"background-color: {member['color']}20; border-left: 3px solid {member['color']}\">\n",
        "                                <div style=\"font-weight: bold; font-size: 0.75em;\">{member['name']}</div>\n",
        "                                <div style=\"font-size: 0.7em; color: #666;\">{schedule['type']}</div>\n",
        "                            </div>\n",
        "                            \"\"\"\n",
        "                            st.markdown(schedule_html, unsafe_allow_html=True)\n",
        "                            if st.button(\"🗑️\", key=f\"del_{schedule['id']}\", help=\"삭제\"):\n",
        "                                delete_schedule(schedule['id'])\n",
        "                                st.rerun()\n",
        "\n",
        "                    if len(day_schedules) > 3:\n",
        "                        st.caption(f\"+{len(day_schedules) - 3}개\")\n",
        "                    current_day += 1\n",
        "                else:\n",
        "                    st.markdown(\"&nbsp;\")\n",
        "        week += 1\n",
        "\n",
        "# 통계 뷰\n",
        "elif st.session_state.view == 'stats':\n",
        "    st.markdown(\"## 📊 통계 대시보드\")\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "    with col1:\n",
        "        st.metric(\"전체 팀원\", f\"{stats['total_members']}명\")\n",
        "    with col2:\n",
        "        st.metric(\"평균 사용 연차\", f\"{stats['avg_used_leave']:.1f}일\")\n",
        "    with col3:\n",
        "        st.metric(\"총 일정 수\", f\"{stats['total_schedules']}건\")\n",
        "    with col4:\n",
        "        most_common = max(stats['type_count'].items(), key=lambda x: x[1])[0] if stats['type_count'] else '-'\n",
        "        st.metric(\"가장 많은 유형\", most_common)\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "    st.markdown(\"### 👥 팀원별 연차 사용 현황\")\n",
        "\n",
        "    for member in members:\n",
        "        remaining = member['total_leave'] - member['used_leave']\n",
        "        percentage = (member['used_leave'] / member['total_leave']) * 100 if member['total_leave'] > 0 else 0\n",
        "        col1, col2 = st.columns([3, 7])\n",
        "        with col1:\n",
        "            st.markdown(f\"**{member['name']}**\")\n",
        "            st.caption(f\"사용: {member['used_leave']}일 | 남은: {remaining}일 | 전체: {member['total_leave']}일\")\n",
        "        with col2:\n",
        "            st.progress(percentage / 100)\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        st.markdown(\"### 📋 일정 유형별 현황\")\n",
        "        if stats['type_count']:\n",
        "            type_df = pd.DataFrame([{'유형': k, '개수': v} for k, v in stats['type_count'].items()])\n",
        "            fig = px.pie(type_df, values='개수', names='유형', hole=0.4)\n",
        "            fig.update_layout(height=400)\n",
        "            st.plotly_chart(fig, use_container_width=True)\n",
        "        else:\n",
        "            st.info(\"등록된 일정이 없습니다.\")\n",
        "\n",
        "    with col2:\n",
        "        st.markdown(\"### 📈 월별 일정 추이\")\n",
        "        if schedules:\n",
        "            schedule_df = pd.DataFrame(schedules)\n",
        "            schedule_df['month'] = pd.to_datetime(schedule_df['date']).dt.to_period('M').astype(str)\n",
        "            monthly_count = schedule_df.groupby('month').size().reset_index(name='count')\n",
        "            fig = px.line(monthly_count, x='month', y='count', markers=True)\n",
        "            fig.update_layout(xaxis_title=\"월\", yaxis_title=\"일정 수\", height=400)\n",
        "            st.plotly_chart(fig, use_container_width=True)\n",
        "        else:\n",
        "            st.info(\"등록된 일정이 없습니다.\")\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "    st.markdown(\"### 📋 전체 일정 목록\")\n",
        "    if schedules:\n",
        "        schedule_list = []\n",
        "        for schedule in schedules:\n",
        "            member = get_member_by_id(schedule['member_id'])\n",
        "            schedule_list.append({\n",
        "                '날짜': schedule['date'],\n",
        "                '팀원': member['name'] if member else '알 수 없음',\n",
        "                '유형': schedule['type'],\n",
        "                '사유': schedule.get('reason', '-')\n",
        "            })\n",
        "        df = pd.DataFrame(schedule_list).sort_values('날짜', ascending=False)\n",
        "        st.dataframe(df, use_container_width=True, hide_index=True)\n",
        "        csv = df.to_csv(index=False, encoding='utf-8-sig')\n",
        "        st.download_button(\"📥 CSV 다운로드\", csv, f\"팀일정_{datetime.now().strftime('%Y%m%d')}.csv\", \"text/csv\")\n",
        "    else:\n",
        "        st.info(\"등록된 일정이 없습니다.\")\n",
        "\n",
        "# 팀원 관리 뷰\n",
        "elif st.session_state.view == 'members':\n",
        "    st.markdown(\"## 👥 팀원 관리\")\n",
        "    st.markdown(\"### 현재 팀원\")\n",
        "\n",
        "    for member in members:\n",
        "        col1, col2, col3, col4 = st.columns([1, 3, 2, 2])\n",
        "        with col1:\n",
        "            st.markdown(f'<div style=\"width: 30px; height: 30px; background-color: {member[\"color\"]}; border-radius: 5px;\"></div>', unsafe_allow_html=True)\n",
        "        with col2:\n",
        "            st.markdown(f\"**{member['name']}**\")\n",
        "        with col3:\n",
        "            st.caption(f\"{member['used_leave']}/{member['total_leave']}일 사용\")\n",
        "        with col4:\n",
        "            remaining = member['total_leave'] - member['used_leave']\n",
        "            st.caption(f\"남은: {remaining}일\")\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "    st.markdown(\"### ➕ 팀원 추가\")\n",
        "\n",
        "    col1, col2, col3 = st.columns(3)\n",
        "    with col1:\n",
        "        new_name = st.text_input(\"이름\")\n",
        "    with col2:\n",
        "        new_total_leave = st.number_input(\"연차 일수\", min_value=0, value=15, step=1)\n",
        "    with col3:\n",
        "        colors = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#EC4899', '#14B8A6', '#F97316']\n",
        "        new_color = st.selectbox(\"색상\", colors)\n",
        "\n",
        "    if st.button(\"팀원 추가\", type=\"primary\"):\n",
        "        if new_name:\n",
        "            new_member = {'name': new_name, 'total_leave': new_total_leave, 'color': new_color}\n",
        "            add_member(new_member)\n",
        "            st.success(f\"{new_name}님이 추가되었습니다!\")\n",
        "            st.rerun()\n",
        "        else:\n",
        "            st.error(\"이름을 입력해주세요.\")\n",
        "\n",
        "st.markdown(\"---\")\n",
        "st.markdown(f\"<div style='text-align: center; color: gray;'>팀 일정 관리 시스템 | {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>\", unsafe_allow_html=True)"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "c1bd9cff"
      },
      "source": [
        "!pip install streamlit"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "57b74d54"
      },
      "source": [
        "# Example of adding a new schedule via code\n",
        "new_schedule_example = {\n",
        "    'member_id': 'some_member_id',  # Replace with an actual member ID\n",
        "    'type': '연차',\n",
        "    'date': '2023-12-25',\n",
        "    'reason': 'Holiday'\n",
        "}\n",
        "\n",
        "add_schedule(new_schedule_example)\n",
        "\n",
        "print(\"New schedule added successfully!\")"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}